service: todo-app-auth

frameworkVersion: "3"

package:
  patterns:
    - "!./**"
    - authorizeWithCognito/index.mjs
    - authorizeWithCognito/node_modules/**

custom:
  remover:
    - ${self.provider.deploymentBucket}

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x

functions:
  authorizeWithCognito:
    handler: authorizeWithCognito/index.handler
    role: authorizeWithCognitoLambdaAtEdgeRole
    memorySize: 128
    timeout: 5

resources:
  Resources:
    authorizeWithCognitoLambdaAtEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: authorizeWithCognitoLambdaAtEdgeRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: authorizeWithCognitoRolePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
